### ISSUE TITLE
Other Сities?

### ISSUE THREAD

**Issue by EvGeniyLell** [denysdovhan/ha-yasno-outages#11]
Is it possible to add other cities, for example, Dnipro? Because now the schedule appears exclusively for Kyiv.

**Comment by denysdovhan** [comment]
Yes it is. We need fetch data for schedule from here: https://api.yasno.com.ua/api/v1/pages/home/schedule-turn-off-electricity

For that we need to refactor `api.py` file. 

If you feel familiar with Python, contributions are welcome!
