### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by AlexGurtoff** [denysdovhan/ha-yasno-outages#40]
Hello, for some reason I can't add integration because there are no city options:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/108fb9af-caa1-4733-aaae-214a8e972d44" />

How can I fix that?
Thank you

**Comment by andrewjswan** [comment]
Look https://github.com/denysdovhan/ha-yasno-outages/pull/32
