### ISSUE TITLE
Consider using remote calendars

### ISSUE THREAD

**Issue by tarik02** [denysdovhan/ha-yasno-outages#7]
I created parser that updates data from yasno on schedule. See:
https://github.com/tarik02/yasno-ics
https://tarik02.github.io/yasno-ics/kyiv/

**Comment by denysdovhan** [comment]
Nice! However, this requires changes to the logic of the component's config_flow. We need to ask user for a city and for a group.

I'll try to do that later, but contributions are welcome!

**Comment by denysdovhan** [comment]
Fixed #12 

Thanks for tiping a URL for an unofficial API!
